function dataOut = convertPartial(dataIn,Phase)

%This function converts between a struct of named column vectors and a
%matrix.

if isstruct(dataIn)
    %Then converting from a struct to a matrix
    switch Phase
        case 'D'
            dataOut = [...
                dataIn.x0,...
                dataIn.y0,...
                dataIn.dx0,...
                dataIn.dy0,...
                ];
        case 'S1'
            dataOut = [...
                dataIn.x0,...
                dataIn.y0,...
                dataIn.x2,...
                dataIn.y2,...
                dataIn.dx0,...
                dataIn.dy0,...
                dataIn.dx2,...
                dataIn.dy2,...
                ];
        case 'S2'
            dataOut = [...
                dataIn.x0,...
                dataIn.y0,...
                dataIn.x1,...
                dataIn.y1,...
                dataIn.dx0,...
                dataIn.dy0,...
                dataIn.dx1,...
                dataIn.dy1,...
                ];
        case 'F'
            dataOut = convert(dataIn);
        otherwise
            error('Phase not supported')
    end
else
    %Then converting from a matrix to a struct
    switch Phase
        case 'D'
            dataOut.x0 = dataIn(:,1);
            dataOut.y0 = dataIn(:,2);
            dataOut.dx0 = dataIn(:,3);
            dataOut.dy0 = dataIn(:,4);
        case 'S1'
            dataOut.x0 = dataIn(:,1);
            dataOut.y0 = dataIn(:,2);
            dataOut.x2 = dataIn(:,3);
            dataOut.y2 = dataIn(:,4);
            dataOut.dx0 = dataIn(:,5);
            dataOut.dy0 = dataIn(:,6);
            dataOut.dx2 = dataIn(:,7);
            dataOut.dy2 = dataIn(:,8);
        case 'S2'
            dataOut.x0 = dataIn(:,1);
            dataOut.y0 = dataIn(:,2);
            dataOut.x1 = dataIn(:,3);
            dataOut.y1 = dataIn(:,4);
            dataOut.dx0 = dataIn(:,5);
            dataOut.dy0 = dataIn(:,6);
            dataOut.dx1 = dataIn(:,7);
            dataOut.dy1 = dataIn(:,8);
        case 'F'
            dataOut = convert(dataIn);
        otherwise
            error('Phase not supported')
    end
end

end